name: LuckyEvent
main: me.choohan.luckyevent.main
version: 4.0
author: choohan
commands:
   LuckyEvent:
      description: A series of event that depends of your lucky!
      aliases: [le]
   LuckyKill:
      description: A series of event that depends of your lucky for kill!
      aliases: [lk]
   LuckyHour:
      description: A series of event that depends of your lucky for playtime!
      aliases: [lh]
   Election:
      description: A series of event that depends of your lucky for election!
      aliases: [el]
   luckyexchange:
      description: A series of event that depends of your lucky for exchange item!
      aliases: [lex]